const NOT_FOUND_STATUS_CODE = 404;
const BAD_REQUEST_STATUS_CODE = 400;
const SERVER_ERROR_STATUS_CODE = 500;
const UNAUTHORIZED_STATUS_CODE = 401;
const FORBIDDEN_STATUS_CODE = 403;

module.exports = {
  NOT_FOUND_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  SERVER_ERROR_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
};
